-- AlterTable
ALTER TABLE "Publication" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "breed" DROP NOT NULL,
ALTER COLUMN "weightInGrams" DROP NOT NULL,
ALTER COLUMN "ageInYears" DROP NOT NULL;
